'use client';

import { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  en: {
    title: "Pradesha Shaba",
    subtitle: "Addalachenai",
    home: "Home",
    services: "Services",
    complaint: "Complaint",
    about: "About Us",
    contact: "Contact",
    signIn: "Sign In",
    register: "Register",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    loggingOut: "Logging out...",
    heroBadge: "OFFICIAL CITIZEN PORTAL",
    heroTitle1: "Citizen Voice.",
    heroTitle2: "Direct Action.",
    heroDesc: "Report community issues, track resolutions in real-time, and build a better municipality together with transparent service delivery.",
    fileBtn: "File a Complaint Now",
    trackBtn: "Track Existing Status",
    servicesBadge: "CIVIC SERVICES PORTAL",
    servicesTitle: "Services We Provide",
    complaintBadge: "TRANSPARENT PROCESS",
    complaintTitle: "How to File a Complaint",
    aboutBadge: "WHO WE ARE",
    aboutTitle: "Digital Civic Authority",
    contactBadge: "DIRECT COMMUNICATION",
    contactTitle: "Get in Touch With Us",
    footerActive: "Online Complaint Portal Active",
    footerNav: "Navigation",
    footerCivic: "Civic Actions",
    footerHelp: "Help & Contact",
    submitNew: "Submit New Complaint",
    trackStatus: "Track Complaint Status",
    citizenReg: "Citizen Registration",
    staffLogin: "Staff / Citizen Login",
    hotline: "Hotline Support",
    emailSupport: "Email Support",
    officeHours: "Office Hours",
    // Services items
    srv_waste_title: "Waste Management",
    srv_waste_desc: "Daily waste collection and proper disposal systems for community",
    srv_street_title: "Street Lighting",
    srv_street_desc: "Maintenance of street lights for safe roads at night",
    srv_drainage_title: "Drainage Systems",
    srv_drainage_desc: "Regular drainage maintenance and blockage resolution",
    srv_roads_title: "Roads & Repairs",
    srv_roads_desc: "Repair damaged roads and maintain safe access routes",
    srv_general_title: "General Support",
    srv_general_desc: "Submit other concerns and suggestions for improvement",
    clickExplore: "Click to Explore →",
    viewDetailsSubmit: "View details & submit →",
    aboutService: "About This Service",
    whatWeInclude: "What We Include",
    fileComplaintFor: "File Complaint for",
    closeBtn: "Close",
    // Steps
    step1_title: "Create Account",
    step1_desc: "Register in seconds using your email or phone number to access the citizen portal securely.",
    step2_title: "File Complaint",
    step2_desc: "Submit your detailed complaint with photos, description, and exact location markers.",
    step3_title: "Track Progress",
    step3_desc: "Monitor live status updates, staff assignments, and receive instant progress notifications.",
    step4_title: "Get Resolution",
    step4_desc: "Receive resolution confirmation report, verify community improvements, and provide feedback.",
    feat1_title: "Fast Processing",
    feat1_desc: "Average response time: 24-48 hours",
    feat2_title: "Secure & Confidential",
    feat2_desc: "Your information is protected and secure",
    feat3_title: "24/7 Access",
    feat3_desc: "File complaints anytime, anywhere",
    // About Us
    aboutCouncilDesc: "The Pradeshiya Sabha - Addalachenai is pioneering a new era of civic administration. By integrating transparent online complaint tracking, rapid dispatch teams, and active citizen participation, we ensure every voice is heard and every public issue is addressed with utmost integrity.",
    digitalAccountability: "Digital Accountability",
    rapidResolution: "Rapid Grievance Resolution",
    futureOutlook: "FUTURE OUTLOOK",
    ourVision: "Our Vision",
    visionDesc: "To build a clean, green, and technologically empowered community where every citizen enjoys superior public services, transparent governance, and an exceptional quality of life.",
    sustainableGrowth: "Sustainable Growth",
    citizenFirst: "Citizen First",
    purposeAction: "PURPOSE & ACTION",
    ourMission: "Our Mission",
    missionDesc: "To deliver prompt, reliable municipal services while safeguarding our environment. We resolve grievances swiftly through real-time digital tracking and active public participation.",
    swiftResolution: "Swift Resolution",
    ecoProtection: "Eco-Protection",
    guidingPrinciples: "GUIDING PRINCIPLES",
    coreValues: "Our Core Values",
    val1_title: "Transparency",
    val1_desc: "Complete openness in decision making and public service reporting.",
    val2_title: "Accountability",
    val2_desc: "Taking total responsibility for timely resolutions and community outcomes.",
    val3_title: "Participation",
    val3_desc: "Empowering residents to voice concerns and co-create local solutions.",
    val4_title: "Innovation",
    val4_desc: "Adopting state-of-the-art digital tools to streamline municipal services.",
    // Contact
    liveHelpdesk: "💬 Live Citizen Helpdesk",
    supportTitle: "We Are Here For Addalachenai 24/7",
    supportDesc: "Our digital support team monitors inquiries around the clock. Whether you need help submitting a grievance, tracking a pending case, or locating public documents, we provide rapid, transparent assistance.",
    instantSupport: "Instant Online Support",
    zeroWait: "Zero Wait Times",
    systemsOperational: "🟢 Systems Operational",
    telHotline: "Telephone Hotline",
    emailDispatch: "Email Dispatch",
    headquarters: "Headquarters",
    workingHours: "Working Hours",
    callHotline: "CALL HOTLINE",
    sendMessage: "SEND MESSAGE",
    viewMaps: "VIEW ON MAPS",
    monFri: "Monday - Friday",
    saturday: "Saturday",
    sundayHolidays: "Sunday & Public Holidays",
    openNow: "OPEN NOW",
    emergencyTitle: "24/7 Emergency Dispatch Active",
    emergencyDesc: "For urgent civic crises (severe flooding, road hazards, water pipe ruptures), our emergency response hotline is staffed 365 days a year.",
    getDirections: "GET INTERACTIVE DIRECTIONS",
    opSchedule: "Operational Schedule",
    activeTimetable: "Active Timetable",
    contactDesc: "Have questions, feedback, or require assistance? Reach out to our dedicated municipal staff through any of our official digital channels below.",
    jurisdictionBadge: "📍 Official Jurisdiction",
    secretariatTitle: "Main Municipal Secretariat",
    secretariatDesc: "Our secretariat serves all citizens of the Addalachenai Pradeshiya Sabha area for public consultations, civic development inquiries, and administrative support.",
    secOffice: "Pradeshiya Sabha Office",
    secAddress: "Addalachenai, Ampara District, Eastern Province, Sri Lanka",
    closedPortalOpen: "Closed • Online Portal Open",
    monSatHours: "Mon-Sat, 8:00 AM - 5:00 PM",
    guaranteed24: "24-Hour Response Guaranteed",
    slAddressShort: "Addalachenai, Sri Lanka",
    monFriHours: "Mon-Fri: 8AM - 5PM",
    emergencyDesk247: "Emergency Desk: 24/7",
    monFriSchedule: "08:00 AM - 05:00 PM",
    satSchedule: "09:00 AM - 01:00 PM"
  },
  ta: {
    title: "பிரதேச சபை",
    subtitle: "அட்டாளைச்சேனை",
    home: "முகப்பு",
    services: "சேவைகள்",
    complaint: "முறைப்பாடு",
    about: "எங்களை பற்றி",
    contact: "தொடர்புக்கு",
    signIn: "உள்நுழைக",
    register: "பதிவு செய்க",
    dashboard: "கட்டுப்பாட்டு அறை",
    profile: "சுயவிவரம்",
    logout: "வெளியேறுக",
    loggingOut: "வெளியேறுகிறது...",
    heroBadge: "அதிகாரபூர்வ குடிமக்கள் தளம்",
    heroTitle1: "குடிமக்கள் குரல்.",
    heroTitle2: "நேரடி நடவடிக்கை.",
    heroDesc: "சமூகப் பிரச்சினைகளை முறையிடுங்கள், தீர்வுகளை உடனுக்குடன் அறிந்து, வெளிப்படையான சேவையுடன் சிறந்த சமூகத்தை உருவாக்குவோம்.",
    fileBtn: "முறைப்பாட்டை பதிவு செய்க",
    trackBtn: "நிலையை அறிதல்",
    servicesBadge: "குடிமக்கள் சேவை தளம்",
    servicesTitle: "நாம் வழங்கும் சேவைகள்",
    complaintBadge: "வெளிப்படையான செயற்பாடு",
    complaintTitle: "முறைப்பாடு பதிவு செய்யும் முறை",
    aboutBadge: "நாம் யார்",
    aboutTitle: "டிஜிட்டல் குடிமக்கள் ஆணைக்குழு",
    contactBadge: "நேரடித் தொடர்பு",
    contactTitle: "எங்களை தொடர்பு கொள்ள",
    footerActive: "இணைய முறைப்பாட்டு தளம் செயற்பாட்டில் உள்ளது",
    footerNav: "வழிசெலுத்தல்",
    footerCivic: "குடிமக்கள் சேவைகள்",
    footerHelp: "உதவி & தொடர்பு",
    submitNew: "புதிய முறைப்பாட்டை பதிவு செய்க",
    trackStatus: "முறைப்பாட்டின் நிலையை அறிதல்",
    citizenReg: "குடிமக்கள் பதிவு",
    staffLogin: "பணியாளர் / குடிமக்கள் நுழைவு",
    hotline: "அவசர உதவி எண்",
    emailSupport: "மின்னஞ்சல் உதவி",
    officeHours: "அலுவலக நேரம்",
    // Services items
    srv_waste_title: "கழிவு முகாமைத்துவம்",
    srv_waste_desc: "தினசரி கழிவு சேகரிப்பு மற்றும் சமூகத்திற்கான முறையான கழிவு அகற்றும் முறைமைகள்",
    srv_street_title: "வீதி விளக்குகள்",
    srv_street_desc: "இரவில் பாதுகாப்பான பயணத்திற்காக வீதி விளக்குகளின் பராமரிப்பு",
    srv_drainage_title: "வடிகாலமைப்பு அமைப்புகள்",
    srv_drainage_desc: "வழக்கமான வடிகாலமைப்பு பராமரிப்பு மற்றும் அடைப்பு நீக்கம்",
    srv_roads_title: "வீதிகள் & திருத்தங்கள்",
    srv_roads_desc: "சேதமடைந்த வீதிகளை திருத்துதல் மற்றும் பாதுகாப்பான வழிகளை பராமரித்தல்",
    srv_general_title: "பொதுவான ஆதரவு",
    srv_general_desc: "மேம்பாட்டிற்கான ஏனைய கவலைகள் மற்றும் ஆலோசனைகளை சமர்ப்பிக்க",
    clickExplore: "மேலும் அறிய அழுத்தவும் →",
    viewDetailsSubmit: "விவரங்களை பார்த்து சமர்ப்பிக்கவும் →",
    aboutService: "இந்த சேவை பற்றி",
    whatWeInclude: "நாம் வழங்குவன",
    fileComplaintFor: "முறைப்பாடு பதிவு:",
    closeBtn: "மூடுக",
    // Steps
    step1_title: "கணக்கை உருவாக்குங்கள்",
    step1_desc: "குடிமக்கள் தளத்தை பாதுகாப்பாக அணுக உங்கள் மின்னஞ்சல் அல்லது தொலைபேசி எண்ணை பயன்படுத்தி சில வினாடிகளில் பதிவு செய்யுங்கள்.",
    step2_title: "முறைப்பாட்டை பதிவு செய்க",
    step2_desc: "புகைப்படங்கள், விவரணம் மற்றும் துல்லியமான இட அடையாளங்களுடன் உங்கள் விரிவான முறைப்பாட்டை சமர்ப்பிக்கவும்.",
    step3_title: "முன்னேற்றத்தை கண்காணிக்கவும்",
    step3_desc: "நேரடி நிலைகள், ஊழியர் நியமனங்கள் மற்றும் உடனடி முன்னேற்ற அறிவிப்புகளை கண்காணிக்கவும்.",
    step4_title: "தீர்வை பெறுங்கள்",
    step4_desc: "தீர்வு உறுதிப்படுத்தல் அறிக்கையை பெற்று, சமூக மேம்பாடுகளை சரிபார்த்து உங்கள் கருத்தை தெரிவிக்கவும்.",
    feat1_title: "விரைவான செயலாக்கம்",
    feat1_desc: "சராசரி மறுமொழி நேரம்: 24-48 மணித்தியாலங்கள்",
    feat2_title: "பாதுகாப்பு & இரகசியம்",
    feat2_desc: "உங்கள் தகவல்கள் முழுமையாக பாதுகாக்கப்படும்",
    feat3_title: "24/7 அணுகல்",
    feat3_desc: "எந்த நேரத்திலும், எங்கிருந்தும் முறைப்பாடுகளை பதிவு செய்யலாம்",
    // About Us
    aboutCouncilDesc: "அட்டாளைச்சேனை பிரதேச சபை குடிமக்கள் நிர்வாகத்தில் ஒரு புதிய சகாப்தத்திற்கு முன்னோடியாக உள்ளது. வெளிப்படையான இணைய முறைப்பாடு கண்காணிப்பு, விரைவான களக் குழுக்கள் மற்றும் தீவிர மக்கள் பங்களிப்பு மூலம், ஒவ்வொரு குரலும் கேட்கப்படுவதையும், ஒவ்வொரு பொதுப் பிரச்சினையும் நேர்மையுடன் தீர்க்கப்படுவதையும் உறுதி செய்கிறோம்.",
    digitalAccountability: "டிஜிட்டல் பொறுப்புக்கூறல்",
    rapidResolution: "விரைவான குறை தீர்வு",
    futureOutlook: "எதிர்கால நோக்கு",
    ourVision: "எமது தூரநோக்கு",
    visionDesc: "ஒவ்வொரு குடிமகனும் சிறந்த பொதுச் சேவைகள், வெளிப்படையான நிர்வாகம் மற்றும் ஒரு விதிவிலக்கான வாழ்க்கை தரத்தை அனுபவிக்கும் ஒரு தூய்மையான, பசுமையான மற்றும் தொழில்நுட்ப ரீதியாக அதிகாரம் பெற்ற சமூகத்தை உருவாக்குதல்.",
    sustainableGrowth: "நிலையான வளர்ச்சி",
    citizenFirst: "குடிமக்களுக்கு முதலிடம்",
    purposeAction: "நோக்கம் & செயற்பாடு",
    ourMission: "எமது பணிக்கூற்று",
    missionDesc: "எமது சுற்றுச்சூழலை பாதுகாக்கும் அதே வேளையில் விரைவான, நம்பகமான நகர சேவைகளை வழங்குதல். நேரடி டிஜிட்டல் கண்காணிப்பு மற்றும் தீவிர மக்கள் பங்களிப்பு மூலம் குறைகளை உடனுக்குடன் தீர்க்கிறோம்.",
    swiftResolution: "விரைவான தீர்வு",
    ecoProtection: "சுற்றுச்சூழல் பாதுகாப்பு",
    guidingPrinciples: "வழிகாட்டும் கோட்பாடுகள்",
    coreValues: "எமது அடிப்படை விழுமியங்கள்",
    val1_title: "வெளிப்படைத்தன்மை",
    val1_desc: "முடிவெடுத்தல் மற்றும் பொது சேவை அறிக்கையிடலில் முழுமையான வெளிப்படைத்தன்மை.",
    val2_title: "பொறுப்புக்கூறல்",
    val2_desc: "ரிய நேரத்திலான தீர்வுகள் மற்றும் சமூக விளைவுகளுக்கு முழுப் பொறுப்பேற்றல்.",
    val3_title: "பங்களிப்பு",
    val3_desc: "குடிமக்கள் தங்கள் கவலைகளை தெரிவிக்கவும் உள்ளூர் தீர்வுகளை உருவாக்கவும் அதிகாரமளித்தல்.",
    val4_title: "புத்தாக்கம்",
    val4_desc: "சபை சேவைகளை நெறிப்படுத்த நவீன டிஜிட்டல் கருவிகளை ஏற்றுக்கொள்வது.",
    // Contact
    liveHelpdesk: "💬 நேரடி குடிமக்கள் உதவிமையம்",
    supportTitle: "அட்டாளைச்சேனைக்காக நாம் 24/7 தயாராக உள்ளோம்",
    supportDesc: "எமது டிஜிட்டல் ஆதரவுக் குழு 24 மணி நேரமும் விசாரணைகளைக் கண்காணிக்கிறது. குறைகளை சமர்ப்பிக்க, முறைப்பாட்டை கண்காணிக்க அல்லது ஆவணங்களைக் கண்டறிய உதவி தேவைப்பட்டாலும், நாம் விரைவான, வெளிப்படையான உதவியை வழங்குகிறோம்.",
    instantSupport: "உடனடி இணைய ஆதரவு",
    zeroWait: "காத்திருப்பு நேரம் இல்லை",
    systemsOperational: "🟢 அமைப்புகள் செயற்பாட்டில் உள்ளன",
    telHotline: "தொலைபேசி அவசர எண்",
    emailDispatch: "மின்னஞ்சல் தொடர்பு",
    headquarters: "தலைமையகம்",
    workingHours: "வேலை நேரங்கள்",
    callHotline: "அழைக்க",
    sendMessage: "செய்தி அனுப்ப",
    viewMaps: "வரைபடத்தில் பார்க்க",
    monFri: "திங்கள் - வெள்ளி",
    saturday: "சனி",
    sundayHolidays: "ஞாயிறு & பொது விடுமுறை நாட்கள்",
    openNow: "தற்போது திறந்துள்ளது",
    emergencyTitle: "24/7 அவசர உதவி சேவை செயற்பாட்டில் உள்ளது",
    emergencyDesc: "அவசர சமூக நெருக்கடிகளுக்கு (கடுமையான வெள்ளம், வீதி அபாயங்கள், நீர் குழாய் வெடிப்பு), எமது அவசர உதவி எண் வருடத்தின் 365 நாட்களும் செயற்படும்.",
    getDirections: "வழிகாட்டலை பெறுக",
    opSchedule: "செயற்பாட்டு அட்டவணை",
    activeTimetable: "செயற்பாட்டு நேரங்கள்",
    contactDesc: "கேள்விகள், கருத்துகள் அல்லது உதவி தேவையா? கீழே உள்ள எமது அதிகாரபூர்வ டிஜிட்டல் வழிகள் மூலம் எமது அர்ப்பணிப்புள்ள நகர சபை பணியாளர்களை தொடர்பு கொள்ளவும்.",
    jurisdictionBadge: "📍 அதிகாரபூர்வ எல்லை",
    secretariatTitle: "முக்கிய நகர சபை செயலகம்",
    secretariatDesc: "எமது செயலகம் அட்டாளைச்சேனை பிரதேச சபை எல்லையில் உள்ள அனைத்து குடிமக்களுக்கும் பொது ஆலோசனைகள், அபிவிருத்தி விசாரணைகள் மற்றும் நிர்வாக ஆதரவுக்காக சேவை செய்கிறது.",
    secOffice: "பிரதேச சபை அலுவலகம்",
    secAddress: "அட்டாளைச்சேனை, அம்பாறை மாவட்டம், கிழக்கு மாகாணம், இலங்கை",
    closedPortalOpen: "மூடப்பட்டது • இணைய தளம் திறந்துள்ளது",
    monSatHours: "திங்கள்-சனி, 8:00 AM - 5:00 PM",
    guaranteed24: "24-மணிநேர பதில் உத்தரவாதம்",
    slAddressShort: "அட்டாளைச்சேனை, இலங்கை",
    monFriHours: "திங்கள்-வெள்ளி: 8AM - 5PM",
    emergencyDesk247: "அவசர பிரிவு: 24/7",
    monFriSchedule: "08:00 AM - 05:00 PM",
    satSchedule: "09:00 AM - 01:00 PM"
  },
  si: {
    title: "ප්‍රාදේශීය සභාව",
    subtitle: "අඩ්ඩාලච්චේනයි",
    home: "මුල් පිටුව",
    services: "සේවා",
    complaint: "පැමිණිලි",
    about: "අප පිළිබඳව",
    contact: "සම්බන්ධ වන්න",
    signIn: "පුරනය වන්න",
    register: "ලියාපදිංචි වන්න",
    dashboard: "පාලන පුවරුව",
    profile: "පැතිකඩ",
    logout: "ඉවත් වන්න",
    loggingOut: "ඉවත් වෙමින්...",
    heroBadge: "නිල පුරවැසි පෝටලය",
    heroTitle1: "පුරවැසි හඬ.",
    heroTitle2: "ඍජු ක්‍රියාමාර්ග.",
    heroDesc: "ප්‍රජා ගැටළු වාර්තා කරන්න, විසඳුම් සජීවීව නිරීක්ෂණය කරමින්, පාරදෘශ්‍ය සේවා සැපයීමක් සමඟ වඩාත් යහපත් පළාත් පාලන ආයතනයක් ගොඩනඟමු.",
    fileBtn: "පැමිණිල්ලක් ඉදිරිපත් කරන්න",
    trackBtn: "තත්ත්වය නිරීක්ෂණය",
    servicesBadge: "පුරවැසි සේවා පෝටලය",
    servicesTitle: "අප සපයන සේවාවන්",
    complaintBadge: "පාරදෘශ්‍ය ක්‍රියාවලිය",
    complaintTitle: "පැමිණිල්ලක් ඉදිරිපත් කරන ආකාරය",
    aboutBadge: "අප පිළිබඳව",
    aboutTitle: "ඩිජිටල් පුරවැසි අධිකාරිය",
    contactBadge: "ඍජු සන්නිවේදනය",
    contactTitle: "අප හා සම්බන්ධ වන්න",
    footerActive: "මාර්ගගත පැමිණිලි පද්ධතිය ක්‍රියාකාරී වේ",
    footerNav: "ගවේෂණය",
    footerCivic: "පුරවැසි සේවා",
    footerHelp: "උපකාර සහ සම්බන්ධතා",
    submitNew: "නව පැමිණිල්ලක් ඉදිරිපත් කරන්න",
    trackStatus: "පැමිණිලි තත්ත්වය නිරීක්ෂණය",
    citizenReg: "පුරවැසි ලියාපදිංචිය",
    staffLogin: "කාර්ය මණ්ඩල / පුරවැසි ප්‍රවේශය",
    hotline: "ක්ෂණික ඇමතුම් සේවාව",
    emailSupport: "විද්‍යුත් තැපැල් සහාය",
    officeHours: "කාර්යාල වේලාවන්",
    // Services items
    srv_waste_title: "අපද්‍රව්‍ය කළමනාකරණය",
    srv_waste_desc: "ප්‍රජාව සඳහා දෛනික අපද්‍රව්‍ය එකතු කිරීම සහ නිසි බැහැර කිරීමේ පද්ධති",
    srv_street_title: "වීදි ආලෝකකරණය",
    srv_street_desc: "රාත්‍රී කාලයේ ආරක්ෂිත මාර්ග සඳහා වීදි පහන් නඩත්තු කිරීම",
    srv_drainage_title: "කාණු පද්ධති",
    srv_drainage_desc: "ක්‍රමවත් කාණු නඩත්තුව සහ අවහිරතා ඉවත් කිරීම",
    srv_roads_title: "මාර්ග සහ අලුත්වැඩියා",
    srv_roads_desc: "හානි වූ මාර්ග අලුත්වැඩියා කිරීම සහ ආරක්ෂිත ප්‍රවේශ මාර්ග පවත්වා ගැනීම",
    srv_general_title: "සාමාන්‍ය සහාය",
    srv_general_desc: "වැඩිදියුණු කිරීම සඳහා වෙනත් ගැටළු සහ යෝජනා ඉදිරිපත් කරන්න",
    clickExplore: "වැඩිදුර තොරතුරු සඳහා ක්ලික් කරන්න →",
    viewDetailsSubmit: "විස්තර බලා ඉදිරිපත් කරන්න →",
    aboutService: "මෙම සේවාව පිළිබඳව",
    whatWeInclude: "අප සපයන දේ",
    fileComplaintFor: "පැමිණිල්ල ඉදිරිපත් කරන්න:",
    closeBtn: "වසන්න",
    // Steps
    step1_title: "ගිණුමක් සාදන්න",
    step1_desc: "පුරවැසි පෝටලයට ආරක්ෂිතව ප්‍රවේශ වීමට ඔබේ විද්‍යුත් තැපෑල හෝ දුරකථන අංකය භාවිතයෙන් තත්පර කිහිපයකින් ලියාපදිංචි වන්න.",
    step2_title: "පැමිණිල්ල ඉදිරිපත් කරන්න",
    step2_desc: "ඡායාරූප, විස්තර සහ නිශ්චිත ස්ථාන සලකුණු සමඟ ඔබේ විස්තරාත්මක පැමිණිල්ල ඉදිරිපත් කරන්න.",
    step3_title: "ප්‍රගතිය නිරීක්ෂණය කරන්න",
    step3_desc: "සජීවී තත්ත්ව යාවත්කාලීන කිරීම්, කාර්ය මණ්ඩල පැවරීම් නිරීක්ෂණය කර ක්ෂණික ප්‍රගති නිවේදනයන් ලබා ගන්න.",
    step4_title: "විසඳුම ලබා ගන්න",
    step4_desc: "විසඳුම් තහවුරු කිරීමේ වාර්තාව ලබා ගන්න, ප්‍රජා වැඩිදියුණු කිරීම් සත්‍යාපනය කර ඔබේ ප්‍රතිපෝෂණය ලබා දෙන්න.",
    feat1_title: "වේගවත් ක්‍රියාවලිය",
    feat1_desc: "සාමාන්‍ය ප්‍රතිචාර කාලය: පැය 24-48",
    feat2_title: "ආරක්ෂිත සහ රහසිගත",
    feat2_desc: "ඔබේ තොරතුරු සම්පූර්ණයෙන්ම ආරක්ෂිතයි",
    feat3_title: "24/7 ප්‍රවේශය",
    feat3_desc: "ඕනෑම වේලාවක, ඕනෑම තැනක සිට පැමිණිලි ඉදිරිපත් කරන්න",
    // About Us
    aboutCouncilDesc: "අඩ්ඩාලච්චේනයි ප්‍රාදේශීය සභාව පුරවැසි පරිපාලනයේ නව යුගයකට පුරෝගාමී වේ. පාරදෘශ්‍ය මාර්ගගත පැමිණිලි ලුහුබැඳීම, වේගවත් ක්‍රියාකාරී කණ්ඩායම් සහ සක්‍රීය පුරවැසි සහභාගීත්වය ඒකාබද්ධ කිරීමෙන්, සෑම හඬකටම සවන් දෙන බවත් සෑම මහජන ගැටලුවක්ම පූර්ණ අවංකභාවයෙන් විසඳන බවත් අපි සහතික කරමු.",
    digitalAccountability: "ඩිජිටල් වගවීම",
    rapidResolution: "වේගවත් ගැටළු විසඳීම",
    futureOutlook: "අනාගත දැක්ම",
    ourVision: "අපගේ දැක්ම",
    visionDesc: "සෑම පුරවැසියෙකුම උසස් රාජ්‍ය සේවාවන්, පාරදෘශ්‍ය පාලනයක් සහ සුවිශේෂී ජීවන තත්ත්වයක් භුක්ති විඳින පිරිසිදු, හරිත සහ තාක්ෂණික වශයෙන් බලගැන්වූ ප්‍රජාවක් ගොඩනැගීම.",
    sustainableGrowth: "තිරසාර වර්ධනය",
    citizenFirst: "පුරවැසියාට මුල්තැන",
    purposeAction: "අරමුණ සහ ක්‍රියාව",
    ourMission: "අපගේ මෙහෙවර",
    missionDesc: "අපගේ පරිසරය ආරක්ෂා කරන අතරම කඩිනම්, විශ්වාසදායක නාගරික සේවාවන් සැපයීම. සජීවී ඩිජිටල් ලුහුබැඳීම සහ සක්‍රීය මහජන සහභාගීත්වය හරහා අපි ගැටළු ඉක්මනින් විසඳන්නෙමු.",
    swiftResolution: "කඩිනම් විසඳුම්",
    ecoProtection: "පරිසර ආරක්ෂණය",
    guidingPrinciples: "මාර්ගෝපදේශක මූලධර්ම",
    coreValues: "අපගේ මූලික වටිනාකම්",
    val1_title: "පාරදෘශ්‍යභාවය",
    val1_desc: "තීරණ ගැනීමේදී සහ රාජ්‍ය සේවා වාර්තා කිරීමේදී පූර්ණ විවෘතභාවය.",
    val2_title: "වගවීම",
    val2_desc: "කාලෝචිත විසඳුම් සහ ප්‍රජා ප්‍රතිඵල සඳහා පූර්ණ වගකීම භාර ගැනීම.",
    val3_title: "සහභාගීත්වය",
    val3_desc: "ගැටළු ප්‍රකාශ කිරීමට සහ දේශීය විසඳුම් නිර්මාණය කිරීමට ප්‍රජාව බලගැන්වීම.",
    val4_title: "නවෝත්පාදනය",
    val4_desc: "සභා සේවාවන් විධිමත් කිරීම සඳහා නවීන ඩිජිටල් මෙවලම් භාවිතය.",
    // Contact
    liveHelpdesk: "💬 සජීවී පුරවැසි සහාය සේවාව",
    supportTitle: "අඩ්ඩාලච්චේනයි වෙනුවෙන් අපි 24/7 සූදානම්",
    supportDesc: "අපගේ ඩිජිටල් සහාය කණ්ඩායම පැය 24 පුරාම විමසීම් නිරීක්ෂණය කරයි. පැමිණිල්ලක් ඉදිරිපත් කිරීමට, පැමිණිල්ලක් ලුහුබැඳීමට හෝ ලේඛන සොයා ගැනීමට උපකාර අවශ්‍ය වුවද, අපි කඩිනම්, පාරදෘශ්‍ය සහාය ලබා දෙන්නෙමු.",
    instantSupport: "ක්ෂණික මාර්ගගත සහාය",
    zeroWait: "රැඳී සිටින කාලයක් නොමැත",
    systemsOperational: "🟢 පද්ධති ක්‍රියාකාරී වේ",
    telHotline: "දුරකථන ක්ෂණික ඇමතුම",
    emailDispatch: "විද්‍යුත් තැපැල් සේවාව",
    headquarters: "මූලස්ථානය",
    workingHours: "කාර්යාල වේලාවන්",
    callHotline: "ඇමතුමක් ගන්න",
    sendMessage: "පණිවිඩයක් යවන්න",
    viewMaps: "සිතියමෙන් බලන්න",
    monFri: "සඳුදා - සිකුරාදා",
    saturday: "සෙනසුරාදා",
    sundayHolidays: "ඉරිදා සහ රජයේ නිවාඩු දින",
    openNow: "දැන් විවෘතයි",
    emergencyTitle: "24/7 හදිසි ප්‍රතිචාර සේවාව ක්‍රියාකාරීයි",
    emergencyDesc: "හදිසි ප්‍රජා ආපදා (දැඩි ගංවතුර, මාර්ග අනතුරු, ජල නල පුපුරා යාම්) සඳහා, අපගේ හදිසි ප්‍රතිචාර සේවාව වසරේ දින 365 පුරාම ක්‍රියාත්මක වේ.",
    getDirections: "මාර්ගෝපදේශ ලබා ගන්න",
    opSchedule: "කාලසටහන",
    activeTimetable: "ක්‍රියාකාරී වේලාවන්",
    contactDesc: "ගැටළු, අදහස් හෝ සහාය අවශ්‍යද? පහත දැක්වෙන අපගේ නිල ඩිජිටල් නාලිකා හරහා අපගේ කැපවූ නගර සභා කාර්ය මණ්ඩලය වෙත සම්බන්ධ වන්න.",
    jurisdictionBadge: "📍 නිල බලප්‍රදේශය",
    secretariatTitle: "ප්‍රධාන නගර සභා ලේකම් කාර්යාලය",
    secretariatDesc: "අපගේ ලේකම් කාර්යාලය මහජන උපදේශන, සංවර්ධන විමසීම් සහ පරිපාලන සහාය සඳහා අඩ්ඩාලච්චේනෛ ප්‍රාදේශීය සභා බලප්‍රදේශයේ සියලුම පුරවැසියන්ට සේවය කරයි.",
    secOffice: "ප්‍රාදේශීය සභා කාර්යාලය",
    secAddress: "අඩ්ඩාලච්චේනෛ, අම්පාර දිස්ත්‍රික්කය, නැගෙනහිර පළාත, ශ්‍රී ලංකාව",
    closedPortalOpen: "වසා ඇත • මාර්ගගත පද්ධතිය විවෘතයි",
    monSatHours: "සඳු-සෙනසු, 8:00 AM - 5:00 PM",
    guaranteed24: "පැය 24 කින් ප්‍රතිචාර සහතිකයි",
    slAddressShort: "අඩ්ඩාලච්චේනෛ, ශ්‍රී ලංකාව",
    monFriHours: "සඳු-සිකු: 8AM - 5PM",
    emergencyDesk247: "හදිසි අංශය: 24/7",
    monFriSchedule: "08:00 AM - 05:00 PM",
    satSchedule: "09:00 AM - 01:00 PM"
  }
};

const LanguageContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
  mounted: false,
});

export const useLanguage = () => useContext(LanguageContext);

export default function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLang = localStorage.getItem('app-lang') || 'en';
    if (translations[savedLang]) {
      setLang(savedLang);
    }
  }, []);

  const handleSetLang = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('app-lang', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, mounted }}>
      {children}
    </LanguageContext.Provider>
  );
}
